project:
  type: website

website:
  title: Hierag Docs
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: changelog.qmd
        text: Changelog
      - href: crawl-scrape-parse-embed.qmd
        text: Crawl/Scrape/Parse/Embed
      - href: hybrid-retrieval.qmd
        text: Hybrid Retrieval
